### ISSUE TITLE
Gather and Process Times

### ISSUE THREAD

**Issue by hegemonia** [amaidah/listings-parser#1]
This is where things get tricky. Yelp communicates operating hours through the webapp in reference to the start of a time period. So like:

Mon	11:00 am - 2:00 am	
Tue	11:00 am - 2:00 am	
Wed	11:00 am - 2:00 am

I'm looking to evaluate hours in reference to the specific day. Therefore, Tuesday in this case (expressed as military time) would be:

Tue 0000 - 0200, 1100 - 2400

The following fields for hours of operation should then be straightforward. I've accounted for up to 3 time-slots per day in this model, but I'm not sure how many places actually would need this many slots. These slots would be placed at the end of the CSV/JSON.

mon_hours_start_1
mon_hours_end_1
mon_hours_start_2
mon_hours_end_2
mon_hours_start_3
mon_hours_end_3
... and etc, for each day of the week.

**Comment by hegemonia** [comment]
As discussed (and in the example above) having overlap (0000 and 2400) is A-ok.

**Comment by amaidah** [comment]
Going to try and have a `start` of midnight be 0000 and an `end` on midnight be 2400. We'll see how easy that is.

**Comment by hegemonia** [comment]
Alternative is 0000 and 2359 if that's not possible, with the -59 suffix only being used for midnight (not for every other endslot).

**Comment by amaidah** [comment]
time and spillover processed
