### ISSUE TITLE
Bug - Issue with spillover times

### ISSUE THREAD

**Issue by hegemonia** [amaidah/listings-parser#10]
The script falls down for certain restaurants, including -
- https://www.yelp.com/biz/the-hat-alhambra

The hypothesis is that it is having trouble if there is spillover for every day of the week (in contrast, https://www.yelp.com/biz/rabbit-hole-alhambra works fine).

**Comment by amaidah** [comment]
Oh, I suspect this is happening because there is no +1 day after Sunday. The script thinks Sunday is the last day so there is no next day field to add the spillover to.

**Comment by amaidah** [comment]
Yup, confirmed script fails at `i = 6` on `times[i + 1].times = range.concat(times[i + 1].times);` because on sunday, `i = 6`, there is no available `i + 1` aka `7`.

**Comment by amaidah** [comment]
fixed issue by adding conditional:

```javascript
          // add time range to start of following day
          if (i < 6) {
            times[i + 1].times = range.concat(times[i + 1].times);
          }
          // handle sunday to add to 'next day' of monday aka times[0]
          else {
            times[0].times = range.concat(times[0].times);
          }
```

The Hat yelp confirmed working
