### ISSUE TITLE
Bug - Inability to handle null phone numbers

### ISSUE THREAD

**Issue by hegemonia** [amaidah/listings-parser#11]
Self-explanatory. Depending on how easy this is to do, might be worth making the script tolerant of null values for any kind of data?

Looks like we're already handling null websites just fine, but I'd imagine that SOME listings might be missing full addresses (if it's a food truck?) and maybe hours?

**Comment by amaidah** [comment]
Do you remember which listing this was?

**Comment by amaidah** [comment]
oh yea, it was temple city green zone

**Comment by amaidah** [comment]
https://www.yelp.com/biz/green-zone-temple-city-3 working
