### ISSUE TITLE
Bug - Issue with apostrophes and ampersands

### ISSUE THREAD

**Issue by hegemonia** [amaidah/listings-parser#12]
"India's Oven" came out as "India&#x2019;s Oven" <--- Looks like github has the same bug. Open this up in edit view.

https://www.yelp.com/biz/indias-oven-los-angeles-2

Similar issue with ampersands: https://www.yelp.com/biz/a-and-j-restaurant-arcadia

If these are difficult to fix, NBD. Manually fixing these isn't too horrible.

**Comment by amaidah** [comment]
Did you mistype? Those two strings look the same?

**Comment by hegemonia** [comment]
Updated.

**Comment by amaidah** [comment]
`India's Oven` came out as `India&#x2019;s Oven` ?

That's the character symbol for right quote hmm

**Comment by amaidah** [comment]
data on log on front end seems fine as it doesn't convert to char symbol on display of string. Assuming there is an issue when converting to csv. Will try converting to string on client side first before sending back to be converted

**Comment by amaidah** [comment]
Actually, looks like it's already in character form on front

**Comment by amaidah** [comment]
Converted `ch('.biz-page-title').html();` to `ch('.biz-page-title').text();`. Looks like in this case grabbing innerHTML was causing the character symbol issue. Grabbing information as text seems to retain apostrophe.

Works for both India's Oven and A & J.

**Comment by amaidah** [comment]
Just as a note, had nothing to do with converting to csv.
