### ISSUE TITLE
Secondary Data

### ISSUE THREAD

**Issue by hegemonia** [amaidah/listings-parser#2]
These bolded fields have been identified as slightly more advanced, and require a little more than simply scraping from a distinct field (the non-bolded fields would have been completed as part of basic data).
- full_name
- short_name: Leave this null
- **phone_number: Stripped formatting (no parentheses, spaces, or dashes)**
- website (url)
- form: Leave this null
- description: Leave this null
- **seating: Default to "Indoors". If there is outdoor seating, use "Mixed"**
- address_street
- address_city
- address_state
- address_zip
- address_country: Leave this null
- **primary: The first cuisine/genre type listed**
- **secondary: The second cuisine/genre type listed**
- cc_accepted: Yes/No
- **budget: Count the dollar signs ("2")**

**Comment by amaidah** [comment]
data gathered
