### ISSUE TITLE
Basic Data

### ISSUE THREAD

**Issue by hegemonia** [amaidah/listings-parser#3]
These bolded fields are the simplest, and should be the starting point for the listings parser. Basically, given a URL for a listing, the tool should gather the following information and output it (in the given order) as a CSV or JSON.

The non-bolded fields are more advanced and will be done in a separate issue.

- **full_name**
- **short_name: Leave this null**
- phone_number: Stripped formatting (no parentheses, spaces, or dashes)
- **website (url)**
- **form: Leave this null**
- **description: Leave this null**
- seating: Default to "Indoors". If there is outdoor seating, use "Mixed"
- **address_one**
- **address_two**
- **address_city**
- **address_state**
- **address_zip**
- **address_country: Leave this null**
- primary: The first cuisine/genre type listed
- secondary: The second cuisine/genre type listed
- **cc_accepted: Yes/No**
- budget: Count the dollar signs ("2")

**Comment by amaidah** [comment]
- address_one
- address_two

Splitting `address street` into the above as discussed to allow for the option to display secondary address information

**Comment by hegemonia** [comment]
Oh right. Updating the description.

**Comment by amaidah** [comment]
data gathered
