### ISSUE TITLE
Enhancement - Obtain Ratings

### ISSUE THREAD

**Issue by hegemonia** [amaidah/listings-parser#4]
This is an enhancement, and can be within (at the end of) the current CSV/JSON or within an additional generated one.

Basically, would like to get a **count** of the ratings distribution, stored within the following fields:
- 1_star
- 2_star
- 3_star
- 4_star
- 5_star

This data can be viewed graphically by clicking on the "details" button next to the Yelp score.

**Comment by amaidah** [comment]
What order? Before times start or at end after times?

**Comment by amaidah** [comment]
at very end as discussed

**Comment by amaidah** [comment]
working as expected on din tai fung and sinbala
